### ISSUE TITLE
Nothing happens after docker run

### ISSUE THREAD

**Issue by passwordleak** [cobbr/Elite#7] opened 2019-03-11 16:01 UTC
user@hostname:/# docker run -it --rm --name elite -v /path/Elite/Elite/Data:/app/Data elite --username AdminUser --computername 0.0.0.0
Password: 
Covenant CertHash (Empty to trust all): <hash> 
user@hostname:/#

It just returns to the shell without doing anything. 
Covenant is running

user@hostname:/# docker run -it -p 7443:7443 -p 8080:8080 -p 8443:8443 --name covenant covenant --username AdminUser --computername 0.0.0.0
Password: 
Found default JwtKey, replacing with auto-generated key...
Creating cert...
Using Covenant certificate with hash: <hash>
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {} may be persisted to storage in unencrypted form.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://+:80'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Production
Content root path: /app
Now listening on: https://0.0.0.0:7443
Application started. Press Ctrl+C to shut down.

Ubuntu 16.04

**Comment by passwordleak** [comment] 2019-03-11 16:09
used the wrong -computername should have been local ip address not 0.0.0.0

**Comment by cobbr** [comment] 2019-03-11 20:50
Glad you got it figured out! It's non-obvious why `localhost` doesn't work as the computername, so I'll leave this open until I include a better error message.

**Comment by cobbr** [comment] 2019-03-11 21:00
Actually nvm, realized this is a duplicate of #5

**Closed as completed by cobbr** 2019-03-11 21:00 UTC
Labels: duplicate
